#pragma once

namespace plt {
    // Faults are spent before the system call: no successful resource is
    // discarded and ownership remains exactly as on a real failure.
    enum class Fault {
        KeymapMap,
        KeymapCompile,
        KeymapState,
        ComposeTable,
        SelectionPipe,
        SelectionFlags,
        SelectionRead,
        SelectionWrite,
        ReadInterrupted,
        WriteInterrupted,
        DisplayLink,
        DisplayCallback,
        PollInterrupted,
        NoClipboard,
        NoPrimary,
        NoTextInput,
        NoViewport,
        NoFractionalScale,
        NoDecoration,
        NoActivation,
        NoCursorShape,
        NoOutput,
        LegacySeat,
        SelectionSetFlags,
        ReadAgain,
        WriteAgain,
        WriteZero,
        FlushInterrupted,
        FlushAgain,
        FlushError,
        DisplayRead,
        DisplayDispatch,
        DisplayConnect,
        XkbContext,
        RegistryRoundtrip,
        NoCompositor,
        NoShell,
        NoSeat,
        LegacyDataDevice,
        PollError,
        WakePipe,
        SignalMask,
        SignalPending,
        CocoaKeySource,
        CocoaKeyLayout,
        CocoaKeyTranslate,
        NoAppAsn,
        NoAppLabel,
        SelectionTimeout,
        WindowSurface,
        FrameCallback,
        LoopFlush,
        SelectionFlush,
        DropFlush,
        SignalWaitInterrupted,
        CocoaMachPort,
        CocoaTimer,
        CocoaDescriptor,
        CocoaWakeSource,
        CocoaDescriptorSource,
        PendingDispatch,
        SignalWaitAgain,
        CocoaDropEncode,
        Count,
    };

    bool chaos(Fault fault);
}
